# Generated by Django 5.0.2 on 2024-02-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('skin_thickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('diabetes_pedigree_function', models.FloatField()),
                ('age', models.IntegerField()),
                ('outcome', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredictCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('gender', models.IntegerField()),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('gluc', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('alco', models.IntegerField()),
                ('active', models.IntegerField()),
                ('cardio', models.BooleanField(default=0)),
            ],
        ),
    ]
