# Generated by Django 5.0.2 on 2024-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_diabetes_user_predictcardio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='pregnancies',
            field=models.IntegerField(default=0),
        ),
    ]
