# Generated by Django 5.0.2 on 2024-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_diabetes_pregnancies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictcardio',
            old_name='weight',
            new_name='Oldpeak',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='active',
            new_name='Sexe',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='alco',
            new_name='Thalassemia',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='ap_hi',
            new_name='blood_sugar',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='ap_lo',
            new_name='chest_pain',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='cholesterol',
            new_name='cholestoral',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='gender',
            new_name='electrocardiographic',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='gluc',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='height',
            new_name='heart_rate',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='smoke',
            new_name='major_vessels',
        ),
        migrations.RenameField(
            model_name='predictcardio',
            old_name='cardio',
            new_name='target',
        ),
        migrations.AddField(
            model_name='predictcardio',
            name='blood_pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictcardio',
            name='slope',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
