# Generated by Django 5.0.3 on 2024-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_weight_predictcardio_oldpeak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='outcome',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='predictcardio',
            name='target',
            field=models.FloatField(default=0),
        ),
    ]
