# Generated by Django 5.0.3 on 2024-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_pneumonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumonia',
            name='image',
            field=models.ImageField(upload_to='photos/%y'),
        ),
    ]
