# Generated by Django 5.0.3 on 2024-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_pneumonia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumonia',
            name='image',
            field=models.ImageField(upload_to='photos/%yyyy'),
        ),
    ]
